/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangeRestDayRouteImport } from './routes/change-rest-day'
import { Route as ChangeTimeScheduleRouteImport } from './routes/change-time-schedule'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as RecordsIdRouteImport } from './routes/records.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRestDayRoute = ChangeRestDayRouteImport.update({
  id: '/change-rest-day',
  path: '/change-rest-day',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeTimeScheduleRoute = ChangeTimeScheduleRouteImport.update({
  id: '/change-time-schedule',
  path: '/change-time-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-rest-day': typeof ChangeRestDayRoute
  '/change-time-schedule': typeof ChangeTimeScheduleRoute
  '/records/$id': typeof RecordsIdRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-rest-day': typeof ChangeRestDayRoute
  '/change-time-schedule': typeof ChangeTimeScheduleRoute
  '/records/$id': typeof RecordsIdRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/change-rest-day': typeof ChangeRestDayRoute
  '/change-time-schedule': typeof ChangeTimeScheduleRoute
  '/records/$id': typeof RecordsIdRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-rest-day'
    | '/change-time-schedule'
    | '/records/$id'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-rest-day'
    | '/change-time-schedule'
    | '/records/$id'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-rest-day'
    | '/change-time-schedule'
    | '/records/$id'
    | '/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangeRestDayRoute: typeof ChangeRestDayRoute
  ChangeTimeScheduleRoute: typeof ChangeTimeScheduleRoute
  RecordsIdRoute: typeof RecordsIdRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-rest-day': {
      id: '/change-rest-day'
      path: '/change-rest-day'
      fullPath: '/change-rest-day'
      preLoaderRoute: typeof ChangeRestDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-time-schedule': {
      id: '/change-time-schedule'
      path: '/change-time-schedule'
      fullPath: '/change-time-schedule'
      preLoaderRoute: typeof ChangeTimeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangeRestDayRoute: ChangeRestDayRoute,
  ChangeTimeScheduleRoute: ChangeTimeScheduleRoute,
  RecordsIdRoute: RecordsIdRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
