/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChooseRouteImport } from './routes/choose'
import { Route as RgcAssetInventoryRouteImport } from './routes/rgc-asset-inventory'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as RgcAssetInventoryIndexRouteImport } from './routes/rgc-asset-inventory.index'
import { Route as RgcAssetInventoryReportsRouteImport } from './routes/rgc-asset-inventory.reports'
import { Route as RgcAssetInventorySettingsRouteImport } from './routes/rgc-asset-inventory.settings'
import { Route as AppChangeOfScheduleIndexRouteImport } from './routes/_app/change-of-schedule/index'
import { Route as AppChangeOfScheduleIdRouteImport } from './routes/_app/change-of-schedule/$id'
import { Route as AppLeaveOfAbsenceIndexRouteImport } from './routes/_app/leave-of-absence/index'
import { Route as AppLeaveOfAbsenceIdRouteImport } from './routes/_app/leave-of-absence/$id'
import { Route as AppOfficialBusinessIndexRouteImport } from './routes/_app/official-business/index'
import { Route as AppOfficialBusinessIdRouteImport } from './routes/_app/official-business/$id'
import { Route as AppOvertimeIndexRouteImport } from './routes/_app/overtime/index'
import { Route as AppOvertimeIdRouteImport } from './routes/_app/overtime/$id'
import { Route as AppRecordsIndexRouteImport } from './routes/_app/records/index'
import { Route as AppRecordsIdRouteImport } from './routes/_app/records/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoute = ChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const RgcAssetInventoryRoute = RgcAssetInventoryRouteImport.update({
  id: '/rgc-asset-inventory',
  path: '/rgc-asset-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const RgcAssetInventoryIndexRoute = RgcAssetInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RgcAssetInventoryRoute,
} as any)
const RgcAssetInventoryReportsRoute =
  RgcAssetInventoryReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => RgcAssetInventoryRoute,
  } as any)
const RgcAssetInventorySettingsRoute =
  RgcAssetInventorySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => RgcAssetInventoryRoute,
  } as any)
const AppChangeOfScheduleIndexRoute =
  AppChangeOfScheduleIndexRouteImport.update({
    id: '/change-of-schedule/',
    path: '/change-of-schedule/',
    getParentRoute: () => AppRoute,
  } as any)
const AppChangeOfScheduleIdRoute = AppChangeOfScheduleIdRouteImport.update({
  id: '/change-of-schedule/$id',
  path: '/change-of-schedule/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveOfAbsenceIndexRoute = AppLeaveOfAbsenceIndexRouteImport.update({
  id: '/leave-of-absence/',
  path: '/leave-of-absence/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveOfAbsenceIdRoute = AppLeaveOfAbsenceIdRouteImport.update({
  id: '/leave-of-absence/$id',
  path: '/leave-of-absence/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOfficialBusinessIndexRoute =
  AppOfficialBusinessIndexRouteImport.update({
    id: '/official-business/',
    path: '/official-business/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOfficialBusinessIdRoute = AppOfficialBusinessIdRouteImport.update({
  id: '/official-business/$id',
  path: '/official-business/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOvertimeIndexRoute = AppOvertimeIndexRouteImport.update({
  id: '/overtime/',
  path: '/overtime/',
  getParentRoute: () => AppRoute,
} as any)
const AppOvertimeIdRoute = AppOvertimeIdRouteImport.update({
  id: '/overtime/$id',
  path: '/overtime/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsIndexRoute = AppRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsIdRoute = AppRecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/choose': typeof ChooseRoute
  '/rgc-asset-inventory': typeof RgcAssetInventoryRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/rgc-asset-inventory/reports': typeof RgcAssetInventoryReportsRoute
  '/rgc-asset-inventory/settings': typeof RgcAssetInventorySettingsRoute
  '/rgc-asset-inventory/': typeof RgcAssetInventoryIndexRoute
  '/change-of-schedule/$id': typeof AppChangeOfScheduleIdRoute
  '/leave-of-absence/$id': typeof AppLeaveOfAbsenceIdRoute
  '/official-business/$id': typeof AppOfficialBusinessIdRoute
  '/overtime/$id': typeof AppOvertimeIdRoute
  '/records/$id': typeof AppRecordsIdRoute
  '/change-of-schedule/': typeof AppChangeOfScheduleIndexRoute
  '/leave-of-absence/': typeof AppLeaveOfAbsenceIndexRoute
  '/official-business/': typeof AppOfficialBusinessIndexRoute
  '/overtime/': typeof AppOvertimeIndexRoute
  '/records/': typeof AppRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/choose': typeof ChooseRoute
  '/profile': typeof AppProfileRoute
  '/rgc-asset-inventory/reports': typeof RgcAssetInventoryReportsRoute
  '/rgc-asset-inventory/settings': typeof RgcAssetInventorySettingsRoute
  '/rgc-asset-inventory': typeof RgcAssetInventoryIndexRoute
  '/change-of-schedule/$id': typeof AppChangeOfScheduleIdRoute
  '/leave-of-absence/$id': typeof AppLeaveOfAbsenceIdRoute
  '/official-business/$id': typeof AppOfficialBusinessIdRoute
  '/overtime/$id': typeof AppOvertimeIdRoute
  '/records/$id': typeof AppRecordsIdRoute
  '/change-of-schedule': typeof AppChangeOfScheduleIndexRoute
  '/leave-of-absence': typeof AppLeaveOfAbsenceIndexRoute
  '/official-business': typeof AppOfficialBusinessIndexRoute
  '/overtime': typeof AppOvertimeIndexRoute
  '/records': typeof AppRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/choose': typeof ChooseRoute
  '/rgc-asset-inventory': typeof RgcAssetInventoryRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/rgc-asset-inventory/reports': typeof RgcAssetInventoryReportsRoute
  '/rgc-asset-inventory/settings': typeof RgcAssetInventorySettingsRoute
  '/rgc-asset-inventory/': typeof RgcAssetInventoryIndexRoute
  '/_app/change-of-schedule/$id': typeof AppChangeOfScheduleIdRoute
  '/_app/leave-of-absence/$id': typeof AppLeaveOfAbsenceIdRoute
  '/_app/official-business/$id': typeof AppOfficialBusinessIdRoute
  '/_app/overtime/$id': typeof AppOvertimeIdRoute
  '/_app/records/$id': typeof AppRecordsIdRoute
  '/_app/change-of-schedule/': typeof AppChangeOfScheduleIndexRoute
  '/_app/leave-of-absence/': typeof AppLeaveOfAbsenceIndexRoute
  '/_app/official-business/': typeof AppOfficialBusinessIndexRoute
  '/_app/overtime/': typeof AppOvertimeIndexRoute
  '/_app/records/': typeof AppRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/choose'
    | '/rgc-asset-inventory'
    | '/profile'
    | '/rgc-asset-inventory/reports'
    | '/rgc-asset-inventory/settings'
    | '/rgc-asset-inventory/'
    | '/change-of-schedule/$id'
    | '/leave-of-absence/$id'
    | '/official-business/$id'
    | '/overtime/$id'
    | '/records/$id'
    | '/change-of-schedule/'
    | '/leave-of-absence/'
    | '/official-business/'
    | '/overtime/'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/choose'
    | '/profile'
    | '/rgc-asset-inventory/reports'
    | '/rgc-asset-inventory/settings'
    | '/rgc-asset-inventory'
    | '/change-of-schedule/$id'
    | '/leave-of-absence/$id'
    | '/official-business/$id'
    | '/overtime/$id'
    | '/records/$id'
    | '/change-of-schedule'
    | '/leave-of-absence'
    | '/official-business'
    | '/overtime'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/choose'
    | '/rgc-asset-inventory'
    | '/_app/profile'
    | '/rgc-asset-inventory/reports'
    | '/rgc-asset-inventory/settings'
    | '/rgc-asset-inventory/'
    | '/_app/change-of-schedule/$id'
    | '/_app/leave-of-absence/$id'
    | '/_app/official-business/$id'
    | '/_app/overtime/$id'
    | '/_app/records/$id'
    | '/_app/change-of-schedule/'
    | '/_app/leave-of-absence/'
    | '/_app/official-business/'
    | '/_app/overtime/'
    | '/_app/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ChooseRoute: typeof ChooseRoute
  RgcAssetInventoryRoute: typeof RgcAssetInventoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose': {
      id: '/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof ChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgc-asset-inventory': {
      id: '/rgc-asset-inventory'
      path: '/rgc-asset-inventory'
      fullPath: '/rgc-asset-inventory'
      preLoaderRoute: typeof RgcAssetInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/rgc-asset-inventory/': {
      id: '/rgc-asset-inventory/'
      path: '/'
      fullPath: '/rgc-asset-inventory/'
      preLoaderRoute: typeof RgcAssetInventoryIndexRouteImport
      parentRoute: typeof RgcAssetInventoryRoute
    }
    '/rgc-asset-inventory/reports': {
      id: '/rgc-asset-inventory/reports'
      path: '/reports'
      fullPath: '/rgc-asset-inventory/reports'
      preLoaderRoute: typeof RgcAssetInventoryReportsRouteImport
      parentRoute: typeof RgcAssetInventoryRoute
    }
    '/rgc-asset-inventory/settings': {
      id: '/rgc-asset-inventory/settings'
      path: '/settings'
      fullPath: '/rgc-asset-inventory/settings'
      preLoaderRoute: typeof RgcAssetInventorySettingsRouteImport
      parentRoute: typeof RgcAssetInventoryRoute
    }
    '/_app/change-of-schedule/': {
      id: '/_app/change-of-schedule/'
      path: '/change-of-schedule'
      fullPath: '/change-of-schedule/'
      preLoaderRoute: typeof AppChangeOfScheduleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/change-of-schedule/$id': {
      id: '/_app/change-of-schedule/$id'
      path: '/change-of-schedule/$id'
      fullPath: '/change-of-schedule/$id'
      preLoaderRoute: typeof AppChangeOfScheduleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-of-absence/': {
      id: '/_app/leave-of-absence/'
      path: '/leave-of-absence'
      fullPath: '/leave-of-absence/'
      preLoaderRoute: typeof AppLeaveOfAbsenceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-of-absence/$id': {
      id: '/_app/leave-of-absence/$id'
      path: '/leave-of-absence/$id'
      fullPath: '/leave-of-absence/$id'
      preLoaderRoute: typeof AppLeaveOfAbsenceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/official-business/': {
      id: '/_app/official-business/'
      path: '/official-business'
      fullPath: '/official-business/'
      preLoaderRoute: typeof AppOfficialBusinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/official-business/$id': {
      id: '/_app/official-business/$id'
      path: '/official-business/$id'
      fullPath: '/official-business/$id'
      preLoaderRoute: typeof AppOfficialBusinessIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overtime/': {
      id: '/_app/overtime/'
      path: '/overtime'
      fullPath: '/overtime/'
      preLoaderRoute: typeof AppOvertimeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overtime/$id': {
      id: '/_app/overtime/$id'
      path: '/overtime/$id'
      fullPath: '/overtime/$id'
      preLoaderRoute: typeof AppOvertimeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/': {
      id: '/_app/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AppRecordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/$id': {
      id: '/_app/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AppRecordsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppChangeOfScheduleIdRoute: typeof AppChangeOfScheduleIdRoute
  AppLeaveOfAbsenceIdRoute: typeof AppLeaveOfAbsenceIdRoute
  AppOfficialBusinessIdRoute: typeof AppOfficialBusinessIdRoute
  AppOvertimeIdRoute: typeof AppOvertimeIdRoute
  AppRecordsIdRoute: typeof AppRecordsIdRoute
  AppChangeOfScheduleIndexRoute: typeof AppChangeOfScheduleIndexRoute
  AppLeaveOfAbsenceIndexRoute: typeof AppLeaveOfAbsenceIndexRoute
  AppOfficialBusinessIndexRoute: typeof AppOfficialBusinessIndexRoute
  AppOvertimeIndexRoute: typeof AppOvertimeIndexRoute
  AppRecordsIndexRoute: typeof AppRecordsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppChangeOfScheduleIdRoute: AppChangeOfScheduleIdRoute,
  AppLeaveOfAbsenceIdRoute: AppLeaveOfAbsenceIdRoute,
  AppOfficialBusinessIdRoute: AppOfficialBusinessIdRoute,
  AppOvertimeIdRoute: AppOvertimeIdRoute,
  AppRecordsIdRoute: AppRecordsIdRoute,
  AppChangeOfScheduleIndexRoute: AppChangeOfScheduleIndexRoute,
  AppLeaveOfAbsenceIndexRoute: AppLeaveOfAbsenceIndexRoute,
  AppOfficialBusinessIndexRoute: AppOfficialBusinessIndexRoute,
  AppOvertimeIndexRoute: AppOvertimeIndexRoute,
  AppRecordsIndexRoute: AppRecordsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RgcAssetInventoryRouteChildren {
  RgcAssetInventoryReportsRoute: typeof RgcAssetInventoryReportsRoute
  RgcAssetInventorySettingsRoute: typeof RgcAssetInventorySettingsRoute
  RgcAssetInventoryIndexRoute: typeof RgcAssetInventoryIndexRoute
}

const RgcAssetInventoryRouteChildren: RgcAssetInventoryRouteChildren = {
  RgcAssetInventoryReportsRoute: RgcAssetInventoryReportsRoute,
  RgcAssetInventorySettingsRoute: RgcAssetInventorySettingsRoute,
  RgcAssetInventoryIndexRoute: RgcAssetInventoryIndexRoute,
}

const RgcAssetInventoryRouteWithChildren =
  RgcAssetInventoryRoute._addFileChildren(RgcAssetInventoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  ChooseRoute: ChooseRoute,
  RgcAssetInventoryRoute: RgcAssetInventoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
