/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppChangeRestDayRouteImport } from './routes/_app/change-rest-day'
import { Route as AppChangeTimeScheduleRouteImport } from './routes/_app/change-time-schedule'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppRecordsIndexRouteImport } from './routes/_app/records/index'
import { Route as AppRecordsIdRouteImport } from './routes/_app/records/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppChangeRestDayRoute = AppChangeRestDayRouteImport.update({
  id: '/change-rest-day',
  path: '/change-rest-day',
  getParentRoute: () => AppRoute,
} as any)
const AppChangeTimeScheduleRoute = AppChangeTimeScheduleRouteImport.update({
  id: '/change-time-schedule',
  path: '/change-time-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsIndexRoute = AppRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsIdRoute = AppRecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/change-rest-day': typeof AppChangeRestDayRoute
  '/change-time-schedule': typeof AppChangeTimeScheduleRoute
  '/profile': typeof AppProfileRoute
  '/records/$id': typeof AppRecordsIdRoute
  '/records/': typeof AppRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/change-rest-day': typeof AppChangeRestDayRoute
  '/change-time-schedule': typeof AppChangeTimeScheduleRoute
  '/profile': typeof AppProfileRoute
  '/records/$id': typeof AppRecordsIdRoute
  '/records': typeof AppRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/change-rest-day': typeof AppChangeRestDayRoute
  '/_app/change-time-schedule': typeof AppChangeTimeScheduleRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/records/$id': typeof AppRecordsIdRoute
  '/_app/records/': typeof AppRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-rest-day'
    | '/change-time-schedule'
    | '/profile'
    | '/records/$id'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/change-rest-day'
    | '/change-time-schedule'
    | '/profile'
    | '/records/$id'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/change-rest-day'
    | '/_app/change-time-schedule'
    | '/_app/profile'
    | '/_app/records/$id'
    | '/_app/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/change-rest-day': {
      id: '/_app/change-rest-day'
      path: '/change-rest-day'
      fullPath: '/change-rest-day'
      preLoaderRoute: typeof AppChangeRestDayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/change-time-schedule': {
      id: '/_app/change-time-schedule'
      path: '/change-time-schedule'
      fullPath: '/change-time-schedule'
      preLoaderRoute: typeof AppChangeTimeScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/': {
      id: '/_app/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AppRecordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records/$id': {
      id: '/_app/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AppRecordsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChangeRestDayRoute: typeof AppChangeRestDayRoute
  AppChangeTimeScheduleRoute: typeof AppChangeTimeScheduleRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordsIdRoute: typeof AppRecordsIdRoute
  AppRecordsIndexRoute: typeof AppRecordsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChangeRestDayRoute: AppChangeRestDayRoute,
  AppChangeTimeScheduleRoute: AppChangeTimeScheduleRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordsIdRoute: AppRecordsIdRoute,
  AppRecordsIndexRoute: AppRecordsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
